### ISSUE TITLE
Generated outputs

### ISSUE THREAD

**Issue by shahbazsyed** [KaiQiangSong/joint_parse_summ#1]
Hi,
Thanks for sharing your code! I want to ask if you can provide the generated summaries of your models for the test set.

**Comment by KaiQiangSong** [comment]
> Hi,
> Thanks for sharing your code! I want to ask if you can provide the generated summaries of your models for the test set.

Check this link:
https://github.com/KaiQiangSong/joint_parse_summ/blob/master/results_joint_parse_summarize.zip
